spring:  application:    name: gateway
server:  port: 8080
eureka:  client:    fetch-registry: true    register-with-eureka: true    serviceUrl:      defaultZone: http://eureka0pri.netsgroup.com:3001/eureka/      zuul:  ignoredServices: '*'  routes:    service1:      path: /service/**      serviceId: GENERIC-SERVICE    